version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ocr-postgres
    environment:
      POSTGRES_DB: ocr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - ocr-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-backend
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ocr-network
    restart: unless-stopped

# Réseau unique et cohérent
networks:
  ocr-network:
    driver: bridge

volumes:
  postgres-data:
